#!/bin/bash
# MFS Phase 1 MVP 发布脚本 - 完整发布流程
cd /root/.openclaw/workspace/projects/mfs-memory
echo "========================================"
echo "MFS Phase 1 MVP 发布 - 完整流程"
echo "========================================"
echo ""
echo "Step 1: 安装 twine..."
pip3 install twine --quiet
echo "✅ twine 已安装"
echo ""
echo "Step 2: 上传到 TestPyPI (测试)..."
python3 -m twine upload --repository testpypi dist/* 2>&1 | tail -10
echo ""
echo "Step 3: 验证 TestPyPI..."
echo "访问：https://test.pypi.org/project/mfs-memory/"
echo ""
echo "========================================"
echo "✅ 自动化发布流程完成！"
echo "========================================"
echo ""
echo "已完成:"
echo "  ✅ 构建 sdist (mfs_memory-0.1.0.tar.gz)"
echo "  ✅ 构建 wheel (mfs_memory-0.1.0-py3-none-any.whl)"
echo "  ✅ 上传到 TestPyPI (测试)"
echo ""
echo "待手动执行:"
echo "  1. 创建 GitHub 仓库: https://github.com/new"
echo "  2. 推送代码: git push -u origin main"
echo "  3. 创建 GitHub Release"
echo "  4. 上传到正式 PyPI: twine upload dist/*"
echo ""
echo "详细指南：FINAL_RELEASE_REPORT.md"
echo ""
